baseURL = "https://thegamingemporium.com/"
languageCode = "en-us"
title = "The Gaming Emporium"

[params]
  description = "A curated list of decompilations, ports, mods, and more."
  cloudflare_web_analytics_token = ""
